### ISSUE TITLE
Feature branch //バインドとエラーメッセージを編集したいがエラーが起きる

### ISSUE THREAD

**Issue by m-suzuki0905** [m-suzuki0905/springboot_Kaitai-Shinsho#4]
## <やりたいこと>

ユーザー登録Formに誕生日と年齢の値を「a」「b」のように[SignupForm.java](https://github.com/m-suzuki0905/springboot_Kaitai-Shinsho/blob/c1d7df818d8e08ff6c5efbfd4bde090ae2c6e422/src/main/java/com/example/form/SignupForm.java#L10)での指定形式以外のフォーマットが入力されたときに[BootStrapのdivを生成](https://getbootstrap.com/docs/4.5/components/forms/#server-side:~:text=button%3E%0A%3C/form%3E-,Server%20side,-We%20recommend%20using)してエラーを出したい
![image](https://user-images.githubusercontent.com/113026626/191020354-47b1194b-35b9-44bd-9b3c-757a66e3fba6.png)

## <エラー内容>
1. [フォーム入力後、登録ボタンを押してもリダイレクトができない](https://github.com/m-suzuki0905/springboot_Kaitai-Shinsho/blob/c1d7df818d8e08ff6c5efbfd4bde090ae2c6e422/src/main/java/com/example/controller/SignupController.java#L40)
 　- SignupController.javaのpostSignupメソッドのリダイレクトとログ出力が起きていない

2. [バインドがうまくいかない](https://github.com/m-suzuki0905/springboot_Kaitai-Shinsho/blob/c1d7df818d8e08ff6c5efbfd4bde090ae2c6e422/src/main/resources/templates/user/signup.html#L15)。誕生日と年齢だけ適当に「文字」を打ってユーザー登録ボタン
     -下記のエラーが出る

### ＜エラーメッセージ＞
<details>
<summary>Console Error</summary>

[org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors<EOL>Field error in object 'signupForm' on field 'age': rejected value [b]; 
codes 
[typeMismatch.signupForm.age,typeMismatch.age,typeMismatch.java.lang.Integer,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: 
codes 
[signupForm.age,age]; arguments []; default message [age]]; 
default message 
[Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'age'; 
nested exception is java.lang.NumberFormatException: For input string: "b"]<EOL>Field error in object 'signupForm' on field 'birthday': rejected value [a]; 
codes [typeMismatch.signupForm.birthday,typeMismatch.birthday,typeMismatch.java.util.Date,typeMismatch]; 

arguments 
[org.springframework.context.support.DefaultMessageSourceResolvable: 
codes 
[signupForm.birthday,birthday]; 
arguments []; 
default message [birthday]]; 
default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'birthday'; 
nested exception is org.springframework.core.convert.ConversionFailedException:Failed to convert from type [java.lang.String] to type [@org.springframework.format.annotation.DateTimeFormat java.util.Date] for value 'a'; nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [a]]]
</details>
<details>

<summary>WhiteLabel Error</summary>

There was an unexpected error (type=Bad Request, status=400).
Validation failed for object='signupForm'. Error count: 2
org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'signupForm' on field 'age': rejected value [b]; 

codes [typeMismatch.signupForm.age,typeMismatch.age,typeMismatch.java.lang.Integer,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: 
codes [signupForm.age,age]; arguments []; default message [age]]; 
default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'age'; 
nested exception is java.lang.NumberFormatException: For input string: "b"]

Field error in object 'signupForm' on field 'birthday': rejected value [a]; 
codes [typeMismatch.signupForm.birthday,typeMismatch.birthday,typeMismatch.java.util.Date,typeMismatch]; 

arguments [org.springframework.context.support.DefaultMessageSourceResolvable: 
codes [signupForm.birthday,birthday]; arguments []; default message [birthday]]; 
default message [Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'birthday'; 
nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@org.springframework.format.annotation.DateTimeFormat java.util.Date] for value 'a'; 
nested exception is java.lang.IllegalArgumentException: Parse attempt failed for value [a]]
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.resolveArgument(ModelAttributeMethodProcessor.java:175)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:122)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:179)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:146)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

</details>

## <考えたこと>
1. ここに関しては`th:object`と`th:field`の使用ミスかなと考えたのですが、html上ではname id共に属性が付与されていたため何が問題なのかイマイチ分からず終いでした。

2. エラーが出た原因としては、
フォームの誕生日と年齢に文字を打ち込んで
Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Integer' for property 'age'
Failed to convert property value of type 'java.lang.String' to required type 'java.util.Date' for property 'birthday';
が返ってきたため、SignupController.javaのpostSignupメソッドのif文がtrueを返しているはずなのですが、
resources>templates>user>signup.htmlに記載してある `th:errorclass`でbootstrapのcssが付与されないためにwhitelabelエラーが出ている？気がするので①、②共に`thymeleafの使い方に問題がある`のかなと考えています。

**Comment by m-suzuki0905** [comment]
formにPostメソッドを追加していないだけだった
